# Generated by Django 2.2.13 on 2020-06-11 00:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ususario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ususario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('atributos', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=18, max_digits=22), size=None)),
                ('codigo_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frecognition.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.IntegerField()),
                ('profesores', models.ManyToManyField(to='frecognition.Profesor', verbose_name='profesores')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('codigo_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frecognition.Clases')),
                ('codigo_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frecognition.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='clases',
            field=models.ManyToManyField(to='frecognition.Clases', verbose_name='clases'),
        ),
    ]
