# Generated by Django 2.2.13 on 2020-06-23 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frecognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='codigo_profesor',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='codigo_alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frecognition.Alumno'),
        ),
    ]
