# Generated by Django 3.0.5 on 2020-05-11 21:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('frecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ususario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('ususario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('clases', models.ManyToManyField(to='frecognition.Clases', verbose_name='clases')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
                ('clases', models.ManyToManyField(to='frecognition.Clases', verbose_name='clases')),
            ],
        ),
    ]
