# Generated by Django 3.0.5 on 2020-05-18 04:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frecognition', '0003_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='atributos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=18, max_digits=22), size=None),
        ),
    ]
