# Generated by Django 3.0.5 on 2020-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frecognition', '0004_auto_20200518_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('nombre_clase', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
